### PR TITLE
added ZXHN H298A

### PR DESCRIPTION
**Pull request by sh5x5j12**
Tested on ZXHN H298A v1 and successfully worked!

### CODE REVIEW

**Comment by mkst** [comment]
Do you have DOS line-endings or something? do you mind changing to LF ? it should only be a 1-line change in the diff

**Comment by sh5x5j12** [comment]
> Do you have DOS line-endings or something? do you mind changing to LF ? it should only be a 1-line change in the diff

What do you mean i didn't understand. I already changed 1 line.

**Comment by mkst** [comment]
Look at the diff: https://github.com/mkst/zte-config-utility/pull/10/files its the whole file identified as being changed.

**Comment by sh5x5j12** [comment]
Oh i see but why it happened i don't know. Actually i just changed one line.

**Pull request closed without merging**
