### PR TITLE
Add support for type 4 with signature-derived key/IV

### PR DESCRIPTION
**Pull request by 811Alex**
This will add support for ZXHN H168N V3.5.
The new key/IV generation is based on another script by Felis-Sapiens.
Tested on files provided by @minanagehsalalma & @kies83.
Fixes https://github.com/mkst/zte-config-utility/issues/11

### CODE REVIEW

**Review by kies83 — APPROVED** [review]

**Comment by 811Alex** [comment]
I'll update encode.py in a bit. Let me know if you want any changes in these, in the meantime.

**Comment by mkst** [comment]
Can the config XML be encrypted for type 4 (without any additional changes)?

**Comment by 811Alex** [comment]
I need to update aes_encrypt() in encryption.py and encode.py. That should be it, though.

**Comment by kies83** [comment]
There is no script yet that can re-encrypt this model's config file.

**Comment by mkst** [comment]
If we can decrypt, why can't we encrypt? Or are you just saying there's no script *yet*?

**Comment by mkst** [comment]
Re: other changes, I don't really like the way is_digi/is_t4 are arguments to `aes_decrypt`, feels very un-SOLID.. but I've not got the time to refactor it. So I'll let it slide..

**Comment by kies83** [comment]
There's no script yet!

**Comment by 811Alex** [comment]
*yet*
this is a draft, I'll add the encryption in a moment

As for the aes_decrypt() arguments, I feel you, but at the same time, they have to get to digi_key() somehow. I'm definitely open to ideas though.

**Comment by 811Alex** [comment]
Would you feel better about it if it was a single Enum?

**Comment by mkst** [comment]
It's fine - next time this function is touched I'll enforce that it's improved :)

Is it possible to add a test/tests for the type 4?

**Comment by 811Alex** [comment]
Added the encryption and the tests.

I also made it byte-perfect, with https://github.com/mkst/zte-config-utility/pull/29/commits/26374c80a7e89b703452c7dddfd3cc52096a6cf6
I compared a couple of type 4s and a couple of type 2s and it seems that type 4s actually set the "unencrypted data length" bytes properly, hence that change. Not the biggest sample, but I think it's good enough for me.

I think that's about it for this one. How does it look?

**Comment by mkst** [comment]
If you're happy with this PR I'll merge it :+1:

**Comment by 811Alex** [comment]
Yup, go for it :)

**Comment by kies83** [comment]
Chapter Close!

**Pull request merged**
